config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/LupoA/lsdensities:
      branch: master
      repo: https://github.com/LupoA/lsdensities
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/LupoA/lsdensities git:
        commands:
        - /usr/bin/env sh .sqa/script.messy-flax-wolverine.sh
        container: qc.acc_trippy-ochre-fox
  QC.Doc:
    repos:
      github.com/LupoA/lsdensities find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-pink-lemur.sh
        container: qc.doc_flabby-brass-newt
      github.com/LupoA/lsdensities git:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-aquamarine-centipede.sh
        container: qc.doc_geeky-burgundy-wildebeest
      github.com/LupoA/lsdensities markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-apricot-lemur.sh
        container: qc.doc_gamy-sapphire-fowl
      github.com/LupoA/lsdensities restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-tangerine-lion.sh
        container: qc.doc_stealthy-harlequin-hornet
  QC.Lic:
    repos:
      github.com/LupoA/lsdensities licensee:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-crimson-bandicoot.sh
        container: qc.lic_scummy-peach-jaguar
  QC.Sec:
    repos:
      github.com/LupoA/lsdensities bandit:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-gamboge-discus.sh
        container: qc.sec_shaggy-ultramarine-cat
  QC.Sty:
    repos:
      github.com/LupoA/lsdensities flake8:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-sangria-bird.sh
        container: qc.sty_gloppy-khaki-fousek
  QC.Uni:
    repos:
      github.com/LupoA/lsdensities pytest:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-tangerine-indri.sh
        container: qc.uni_snazzy-blue-bear
  QC.Ver:
    repos:
      github.com/LupoA/lsdensities get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-jade-caracal.sh
        container: qc.ver_droopy-violet-cat
timeout: 5400
