config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/LupoA/lsdensities:
      branch: master
      repo: https://github.com/LupoA/lsdensities
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/LupoA/lsdensities git:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-rust-dhole.sh
        container: qc.acc_pasty-aqua-bulldog
  QC.Doc:
    repos:
      github.com/LupoA/lsdensities find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-xanthic-foxhound.sh
        container: qc.doc_surly-denim-rattlesnake
      github.com/LupoA/lsdensities git:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-jade-zebra.sh
        container: qc.doc_shaggy-gamboge-urchin
      github.com/LupoA/lsdensities markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-malachite-frigatebird.sh
        container: qc.doc_thirsty-turquoise-mandrill
      github.com/LupoA/lsdensities restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-cobalt-raccoon.sh
        container: qc.doc_leaky-cream-drever
  QC.Lic:
    repos:
      github.com/LupoA/lsdensities licensee:
        commands:
        - /usr/bin/env sh .sqa/script.beady-lavender-meerkat.sh
        container: qc.lic_craggy-cream-dragonfly
  QC.Sec:
    repos:
      github.com/LupoA/lsdensities bandit:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-scarlet-yak.sh
        container: qc.sec_wheezy-blue-slug
  QC.Sty:
    repos:
      github.com/LupoA/lsdensities flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-harlequin-booby.sh
        container: qc.sty_lumpy-smalt-oriole
  QC.Uni:
    repos:
      github.com/LupoA/lsdensities pytest:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-cerise-anteater.sh
        container: qc.uni_snoopy-viridian-kiwi
  QC.Ver:
    repos:
      github.com/LupoA/lsdensities get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-russet-paradise.sh
        container: qc.ver_dorky-russet-abyssinian
timeout: 5400
